### ISSUE TITLE
Matt's Github Issue

### ISSUE THREAD

**Issue by gdykeman** [napsda/napsda.github.io#1]
Created by Gerald Dykeman via monday.com integration. 🎉

**Comment by l3acon** [comment]
Currently, we do not have the ability to link directly to a "Demo" or workshop or whatever, you can only link to the "Content" group. Eg. https://napsda.github.io/ansible/ansible.html . It would be nice to be able to send individual links to peeps.

**Comment by gdykeman** [comment]
@l3acon does this resolve the issue? 
commit 1a2329edbf62ecfead428d98c7d6053dd7d6b45b

Feel free to close out if we're good
